#security:
#  basic:
#    enabled: false

info:
  app:
    name: spase-api-boilerplate

server:
  port: ${SERVER_PORT:80}

feign.httpclient.enabled: false

spase.client:
  gatewayHost: ${GATEWAY_HOST}

logging:
  level:
    root: INFO
    feign: DEBUG

spring:
  redis:
    host: 127.0.0.1
    port: 6379
  profiles:
    active: production
